// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBd54PyjFZ7A2bPwX2WTbrQ3gmMflN0KHg',
    appId: '1:807843638675:web:8bf6a341f2adc2b6fd8c66',
    messagingSenderId: '807843638675',
    projectId: 'mogapapushnotification',
    authDomain: 'mogapapushnotification.firebaseapp.com',
    storageBucket: 'mogapapushnotification.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNz0C6JNOqvdd7TcPyYnJuwnuFsdUQts0',
    appId: '1:807843638675:android:06b598d60490017cfd8c66',
    messagingSenderId: '807843638675',
    projectId: 'mogapapushnotification',
    storageBucket: 'mogapapushnotification.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzVyHFDo6C6xkZcX4IcUXdK4i23wkaUi4',
    appId: '1:807843638675:ios:23e72226642c9b1efd8c66',
    messagingSenderId: '807843638675',
    projectId: 'mogapapushnotification',
    storageBucket: 'mogapapushnotification.appspot.com',
    iosBundleId: 'com.example.ui',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzVyHFDo6C6xkZcX4IcUXdK4i23wkaUi4',
    appId: '1:807843638675:ios:c31f0a8a6baeb868fd8c66',
    messagingSenderId: '807843638675',
    projectId: 'mogapapushnotification',
    storageBucket: 'mogapapushnotification.appspot.com',
    iosBundleId: 'com.example.ui.RunnerTests',
  );
}
